### ISSUE TITLE
Shop & Upgrade Villagers despawned when a player killed an enemy.

### ISSUE THREAD

**Issue by xwertxy** [Sergittos/BedWars#34] opened 2024-02-13 13:33 UTC
**Describe the bug**
Shops has despawned when a player killed an enemy (other team), seems like the chunk generation issue between entities.

**To Reproduce**
- Join in the server, go start the game with other player
- Kill them at the middle of the map, when they spawned, the part of chunk of the player where team is set has been reseted or removed.
- Entity will also removed/despawned.

**Additional context**
It seems like the chunk with entities has not to be saved in that certain chunk, which probably caused entity despawned. I was thinking of how map is resetted (even the player that placed blocks are gone too.)

**Comment by xwertxy** [comment] 2024-02-13 13:34
Also, i've been noticing between other teams that are null, no one alive, and yeah we can break also bed and get the item.

**Comment by Sergittos** [comment] 2024-02-16 18:53
It doesn't happen to me, are you using a modified PocketMine version?

**Comment by UnknownNull** [comment] 2024-02-16 19:49
> Also, i've been noticing between other teams that are null, no one alive, and yeah we can break also bed and get the item.
> 
> This is the probably fix for that.

No, this is related to large maps, when the player moves away from the chunk where the villager is, that chunk is unloaded, and when the player returns to it in any way, such as being killed or walking, other villagers and blocks that was placed around the bed is not there.

**Comment by UnknownNull** [comment] 2024-02-16 19:51
To make this happen to you a lot, just reduce `view-distance` =[

**Comment by xwertxy** [comment] 2024-02-17 02:30
> > Also, i've been noticing between other teams that are null, no one alive, and yeah we can break also bed and get the item.
> > This is the probably fix for that.
> 
> No, this is related to large maps, when the player moves away from the chunk where the villager is, that chunk is unloaded, and when the player returns to it in any way, such as being killed or walking, other villagers and blocks that was placed around the bed is not there.

This happends when entity is not saved through chunks.

**Comment by xwertxy** [comment] 2024-02-17 02:31
> It doesn't happen to me, are you using a modified PocketMine version?

No i am originally PocketMine-MP from stable releases. I've been also tried without any using other plugins.

**Comment by xwertxy** [comment] 2024-02-17 02:36
I'll send later the attachment to reproduce this issue.

**Comment by UnknownNull** [comment] 2024-02-17 12:01
> I'll send later the attachment to reproduce this issue.

I even sent a video in this regard, but it was ignored by him 👈(ﾟヮﾟ👈)

**Comment by Sergittos** [comment] 2024-02-17 14:56
I'm unable to reproduce this issue, anyways I'm going to change the way the worlds are created for the games

**Comment by UnknownNull** [comment] 2024-02-17 15:02
> I'm unable to reproduce this issue, anyways I'm going to change the way the worlds are created for the games

I think the "UnloadChunkEvent" event will solve the problem easily ＼（〇_ｏ）／

**Comment by Sergittos** [comment] 2024-02-17 15:08
Yes, cancelling UnloadChunkEvent would fix this problem, but I don't think that's the right way to fix it.

I don't like the current game generation system, so I'm going to change the way they are generated and that will fix this problem

**Comment by UnknownNull** [comment] 2024-02-17 15:12
> Yes, cancelling UnloadChunkEvent would fix this problem, but I don't think that's the right way to fix it.
> 
> I don't like the current game generation system, so I'm going to change the way they are generated and that will fix this problem

How can you prevent the chunk from being unloaded with a different construction method?

**Comment by Sergittos** [comment] 2024-02-17 15:16
The current game generation system sets the world auto save to false, which means that chunks that are unloaded won't be saved.

In the new game generation system this won't happen, so this problem will be solved.

**Comment by xwertxy** [comment] 2024-02-18 05:28
Here's a breif reproduce of issue. I just modified only the scoreboard and the rest including xp bar is on another plugin. 

https://streamable.com/uq2por

**Comment by UnknownNull** [comment] 2024-02-18 14:59
> The current game generation system sets the world auto save to false, which means that chunks that are unloaded aren't saved.
> 
> In the new game generation system this won't happen, so this problem will be solved.

This bug was also in this plugin:
https://github.com/boi1216/BedWarsUltimate
although its reset map system was different from your plugin

**Comment by xwertxy** [comment] 2024-02-24 08:19
> Blocks placed by the player on their island may also disappear along with the villagers despawning

Pocketmine chunk issue

**Comment by Sergittos** [comment] 2024-03-05 17:11
Fixed in 1.0.9, thanks for reporting!

**Closed by Sergittos** 2024-03-05 17:11 UTC
Labels: Category: Bug, Status: Unconfirmed
